### ISSUE TITLE
Quick Start with GKE Problems

### ISSUE THREAD

**Issue by hklai** [istio/istio.github.io#1249]
1. The IAM screenshot needs to be updated (the UI had changed).

2. Deploying using Launch Deployment Manager failed with the following foe me.

istio-cluster-1 has resource warnings
istio-cluster: {"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Version \"1.9.6-gke.0\" is invalid.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/hklai-istio-testing/zones/us-central1-a/clusters","httpMethod":"POST"}}
istio-cluster-1-istio-cluster-1-waiter: {"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

![9oht52qysvz](https://user-images.githubusercontent.com/31747472/39731009-ce6ae25c-5219-11e8-8926-9924515a733f.png)

**Comment by geeknoid** [comment]
@salrashid123 do you want to update this doc page?

**Comment by prabuddhg** [comment]
@salrashid123 Thanks for your comments. I was unable to find the "Location" drop-down option.

Do you see the option "Location" when you click "Istio GKE Deployment Manager" from page 

The reason I am asking this question is that istio cluster deployment failed for me with this issue:

istio-cluster-1 has resource warnings
istio-cluster-1-istio-cluster-1-waiter: {"ResourceType":"runtimeconfig.v1beta1.waiter","ResourceErrorCode":"504","ResourceErrorMessage":"Timeout expired."}

Please let me know if this is a known issue and if there is a workaround.

https://istio.io/docs/setup/kubernetes/quick-start-gke-dm.html
![screen shot 2018-05-23 at 10 29 38 pm](https://user-images.githubusercontent.com/11824431/40466105-d5e95272-5ed8-11e8-87f1-e4c02fa9400e.png)

**Comment by salrashid123** [comment]
@prabuddhg  hi-

The screenshot i provided above isn't from the 'quick-start'; its just the plain GKE configurtion settings on the GCP cloud console (its just there to list the active versions that are available).

In your case, I"m not sure what the issue would be here (debugging the DM setup is challenging since we can't surface the underlying error easily to you).  
I'd suggest precisely verifying the [prerequisites](https://istio.io/docs/setup/kubernetes/quick-start-gke-dm.html#prerequisites)  ...especially the ```roles/container.admin``` for the DM service account

**Comment by salrashid123** [comment]
yeah, this one can get closed out.    it was addressed on 
https://github.com/istio/istio.github.io/pull/1260

however, we still need to update the docs (i think there's some minor formatting and what not to address; we'll handle that on issue#1786)
