### ISSUE TITLE
Please stop istioldie and prelim from appearing in Google search results

### ISSUE THREAD

**Issue by craigbox** [istio/istio.github.io#1536]
We should ask web crawlers not to index documentation that is not from the current release. This applies especially to preliminary, but I've seen it with old versions too.

- search for "istio multicluster" on Google, see 1.0 docs above 0.8 docs
- search for "istioldie" on Google, see results, expect none

![istio-search-results](https://user-images.githubusercontent.com/132510/41539174-04452700-7305-11e8-8daa-20255923debc.png)

**Comment by geeknoid** [comment]
I updated the robots.txt file on preliminary.istio.io, but not on archive.istio.io. This is because we do want the archive to be indexed so it can be searched. If I disallow robots on the archive site, then we wouldn't be able to use the site's own search function (which depends on robots crawling the site)
