### ISSUE TITLE
Issues with the RSS feed

### ISSUE THREAD

**Issue by craigbox** [istio/istio.github.io#1537]
a) When you go to /blog/, you are given a "subscribe" link to https://istio.io/feed.xml.  That contains all the posts in oldest-first, where I would expect it to show them in newest-first.

b) Every few days lately, recent items have been reappearing in the feed, out of order:

<img width="1534" alt="screen shot 2018-06-18 at 2 42 40 pm" src="https://user-images.githubusercontent.com/132510/41539604-1a0cccea-7306-11e8-8d0e-eedbf5f2660a.png">

I presume when the site is being regenerated the feed is being updated without IDs that let feed readers know that the items are the same as the ones before.

c) The model of using preliminary.istio.io meant that posts in April (and perhaps the one in Feb) weren't published on the main feed, or the main web site, until Istio 0.8 was released. This is almost certainly not what you wanted.

Can we separate /blog/ from the rest of the Istio site and run it like a blog?

**Comment by geeknoid** [comment]
Hi,

I'll have a fix for the ordering issue shortly. As for your #2 point, I don't know why that would happen. Each item is tagged with a unique id (it's URL). We changed our URL generation approach in 0.8 (pretty vs ugly URLs) so maybe that's the issue.

I also found that the publication date format we used was incorrect. Maybe that's why your feed items weren't listed in the correct order in the first place.

Finally, about the publication process, we just need to be diligent about publishing the blog to both the master branch and the current release branch, and then the post will show up at the right time.
