### ISSUE TITLE
Consider using kubectl instead of istioctl for all CRUD operations

### ISSUE THREAD

**Issue by ymesika** [istio/istio.github.io#1843]
@ozevren commented on [Mon Jul 16 2018](https://github.com/istio/istio/issues/7163)

https://preliminary.istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes

"Define the ingress gateway for the application" step is using istioctl, whereas all other commands are kubectl. Use of istioctl is not necessary as it does "-f apply".

---

@ozevren commented on [Mon Jul 16 2018](https://github.com/istio/istio/issues/7163#issuecomment-405369763)

istioctl is not necessary in the uninstall/kubernetes steps.

**Comment by ymesika** [comment]
First comment seems to be fixed by #1837 
For the 2nd comment, do you mean that Confirm shutdown is not necessary?

**Comment by ozevren** [comment]
No, the page is using a mix of istioctl & kubectl. Use of istioctl is not necessary. It is better to simply use one (i.e. kubectl).

**Comment by frankbu** [comment]
We encourage people to use istioctl instead of kubectl for Istio specific resources. Better validation and command output. I'm not sure what the benefit is of trying to keep istioctl out of the picture entirely. I agree that it makes sense to create the Gateway using kubectl, since that's sort of just another deployment step, but cleanup makes more sense to stick to istioctl commands, since all the tasks that create those resources use istioctl. Also, the cleanup.sh script uses istioctl.

**Comment by ozevren** [comment]
We already have a validation webhook getting installed as part of standard deployment. Is the kubectl output for gateway and virtualservice is considered bad? (I didn't feel that way, but I am not the customer).

Sticking to a single command-line tool in the tasks will be less confusing, given that the user is already learning through new concepts. Kubectl seems to be more heavily used on the page, and it seems like it can be used for everything else as well. Switching tools mid-flow is distracting, especially with no indication of why or whether it is required.

**Comment by frankbu** [comment]
Good point about the validation, I guess that excuse is no longer valid :-)

`istioctl get` commands are certainly a better choice than `kubectl get`:
```
$ kubectl get virtualservices
NAME          AGE
bookinfo      1d
details       1d
productpage   1d
ratings       1d
reviews       1d
$ istioctl get virtualservices
VIRTUAL-SERVICE NAME   GATEWAYS           HOSTS         #HTTP     #TCP      NAMESPACE   AGE
bookinfo               bookinfo-gateway   *                 1        0      default     1d
details                                   details           1        0      default     1d
productpage                               productpage       1        0      default     1d
ratings                                   ratings           1        0      default     1d
reviews                                   reviews           1        0      default     1d
```

That said, for cleanup, they are both expected to simply return `No resources found`.

But ... I have just made this worse with https://github.com/istio/istio.github.io/pull/1885, where there are now instructions in the bookinfo sample to create and display destinationrules.

So, personally I'm leaning towards leaving the mix of commands in the instructions. I know that it was documented somewhere that in a kube env, users can use `kubectl` instead of `istioctl` for all of the commands.

Maybe a more prominent statement to that effect in the bookinfo instructions would be a good enough compromise.

Does anybody else have a strong opinion on this?

**Comment by ayj** [comment]
API resource categories is already supported today with Istio 1.0 on kube-apiserver >= 1.10 (see below).  

```bash
kubectl get istio-io                # get all istio configuration

kubectl get networking-istio-io     # get networking configuration
kubectl get authentication-istio-io # get authentication configuration
kubectl get policy-istio.io         # get policy (mixer) configuration
kubectl get rbac-istio-io           # get rbac related configuration
kubectl get api-istio-io            # get API management related configuration
```
Here's a current breakdown of istioctl CRUD operation usage. 

```bash
$ grep -rn -e "istioctl create" content | wc -l
89
$ grep -rn -e "istioctl get" content | wc -l
25
$ grep -rn -e "istioctl replace" content | wc -l
26
$ grep -rn -e "istioctl delete" content | wc -l
54
```

AFAICT, there's only one place in the docs that relies on the custom column output [here](https://preliminary.istio.io/docs/examples/bookinfo/#apply-default-destination-rules). Everything else uses `-o yaml` option to inspect the full API resources.
