### ISSUE TITLE
Fix "Before you begin" section in tasks/request-routing.md

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.github.io#185]
From hackathon feedback:

The instructions for tasks “Configuring Request Routing” and “Fault Injection” should have “istioctl replace” instead of “istioctl create” for the route rules. Rerunning create will fail otherwise.

This is an issue for all tasks. 
We should have common verbiage that addresses it everywhere.

**Comment by LisaFC** [comment]
So do we want to use istiocl replace even for the initial settings ie 

istioctl create -f samples/apps/bookinfo/route-rule-all-v1.yaml
istioctl create -f samples/apps/bookinfo/route-rule-reviews-test-v2.yaml

Are we using replace because there are already policies and rules set that we're replacing? The impression given in the text is that there isn't a default route already set when you install the sample and it will more or less randomly distribute traffic between versions. Or are we assuming people will do this exercise more than once? Or is this text already fixed in a previous PR?

(Also why do we have separate create and replace commands to specify rules? Is it because there are situations where we want create to fail if there's already a rule set?)

**Comment by frankbu** [comment]
@LisaFC create and replace both have semantics that will fail if the initial state isn't right (create if the rule already exists, replace if it does not exist). Even though there is a suggested order to go through the tasks, any task should work on its own at any time. I handled this issue in the rate-limiting task with a Note (https://istio.io/docs/tasks/rate-limiting.html), since it only applies when users are not doing tasks in order. Maybe we should do the same in the other ones?

**Comment by LisaFC** [comment]
OK, that makes sense. And yes, the note or similar is a perfect solution - basically that we're assuming you haven't already set this, but if you have you need to use replace because otherwise the command will fail

**Comment by LisaFC** [comment]
Which tasks do I need to add the note to? "Request Routing", "Fault Injection" (just for the setting up default routes bit at the top, yes, not the fault injection rule, or both?)? Anything else?

**Comment by LisaFC** [comment]
Oh hang on, it's in Request Timeouts as well.

**Comment by LisaFC** [comment]
Fixed in https://github.com/istio/istio.github.io/pull/373
