### ISSUE TITLE
Get rid of all the white space at the bottom of documents

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#233]
Individual documents on the Istio site have a huge amount of whitespace at the bottom. I don't know where that's coming from, but it's odd and I think should be nuked.

**Comment by davetropeano** [comment]
This was being caused by some javascript in the tabbed sidebar slider but I have no idea why it was adding so much padding -- it was only supposed to be 50px max.

I removed this and had to clean up some other things in that JS in order to get it to lay out properly without the padding. Check the referenced PR

**Comment by davetropeano** [comment]
There is still 60px of `padding-bottom` being added by the `markdown` class which is legacy. We can keep it or can adjust to be smaller as you see fit.
