### ISSUE TITLE
Rationalize font sizes

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#282]
We should rationalize all uses of font-size, font-weight, and line-height within the web site.

Instead of being defined in terms of pixels, all these need to be defined throughout in terms of em such that proper scaling takes place on devices with different pixel density.

_sass/base/_config.scss defines the core font sizes we want to use. Any place setting a font-size property should be using one of those variables. We probably should provide a similar set of variables for font weight and line height and use those everywhere in CSS land.

**Comment by davetropeano** [comment]
In general, yes -- but be careful what you wish for because once you try and put all fonts in terms of em or rem units you will find some spacing problems with containers, etc. One of the previous issues for example was because fonts *were* in rem units (relative em) and on certain display orientations it caused a few pixels of issues. 

My point here is that you may end up biting off a lot of additional css breakpoints for a doc site

**Comment by geeknoid** [comment]
Fixed by PR #826
