### ISSUE TITLE
Issue with _docs/tasks/installing-istio.md

### ISSUE THREAD

**Issue by knutster** [istio/istio.github.io#354]
Don't forget that when a user is using minikube it is possible to easily view a service via the minikube command.

# minikube service list  -- gives a list of services and urls

# minikube service grafana -- opens a browser tab to grafana

# minikube service istio-ingress -- opens a browser tab to the ingress controller

**Comment by andraxylia** [comment]
Can you provide more details on this issue and how it relates to installing istio? It's not clear from the description.

**Comment by frankbu** [comment]
I think @knutster is suggesting that we could mention in the docs that when using minikube there are some convenient commands that you can use to find the nodeport of the services.

The most useful feature, IMO, would be `minikube service istio-ingress` to open a browser to the ingress controller but it doesn't work well in our case since we have 2 service ports (http and https) and we need to open the browser to `/productpage`, instead of `/`. 

So, I'm closing because I don't think it's worth adding the extra clutter in the docs.
